name: Deploy
run-name: Deploy to S3
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: checkou
        uses: actions/checkout@v2
      
      - name: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: install packages
        run: |
          npm install

      - name: build Next.js
        run: |
          npm run build

      - name: export Next.js
        run: |
          npm run export

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Upload file to S3
        run: |
          aws s3 cp out/ s3://${{ secrets.S3_UPLOAD_BUCKET }}/ --recursive